package:
  name: colomoto
  version: "0.2.2"

requirements:
  run:
    - python   >=3.6,<3.7
    - openjdk  >=8.0,<9
    - notebook >=5.2
    - nusmv    2.6.0
    - clingo   5.2.2
    - ginsim   2.9.6
    - maboss   2.0
    - pint     2017.09.25
    - ginsim-python 0.2.1
    - pypint   1.3.1
    - colomoto_jupyter 0.3.4

build:
  noarch: generic

about:
  home:  http://colomoto.org/


