package:
  name: colomoto
  version: "0.2.1"

requirements:
  run:
    - python   3.6
    - openjdk  8.0
    - clingo   5.2
    - nusmv    2.6
    - notebook 5.2
    - ginsim   2.9.6
    - ginsim-python 0.2
    - maboss   2.0
    - pypint   1.3.1

build:
  noarch: generic

about:
  home:  http://colomoto.org/


