package:
  name: colomoto
  version: "0.1"

source:
  git_url: https://github.com/colomoto/colomoto-api.git

build:
  noarch: python

requirements:
  run:
    - python
    - ginsim
    - maboss
    - notebook
    - py4j

about:
  home:  http://colomoto.org/


