package:
  name: colomoto
  version: "0.2.15"

channels:
  - bioconda
  - conda-forge
  - potassco
  - colomoto

requirements:
  run:
    - notebook
    - nusmv
    - nusmv-arctl
    - clingo
    - its
    - ginsim-python
    - pypint
    - colomoto_jupyter
    - pymaboss
    - mpbn

build:
  noarch: generic

about:
  home:  http://colomoto.org/
