package:
  name: colomoto
  version: "0.2"

requirements:
  run:
    - python
    - notebook
    - ginsim-python
    - maboss
    - pypint

build:
  noarch: generic

about:
  home:  http://colomoto.org/


