package:
  name: colomoto
  version: "0.2.17"

channels:
  - bioconda
  - conda-forge
  - potassco
  - colomoto

requirements:
  run:
    - notebook
    - nusmv
    - nusmv-arctl
    - clingo
    - its
    - ginsim-python
    - pypint
    - colomoto_jupyter
    - pymaboss
    - mpbn
    - casq
    - rpy2
    - r-boolnet
    - bioconductor-cellnoptr
    - bioconductor-cnorode
    - bioconductor-cnorfeeder
    - bioconductor-cnordt
    - bioconductor-cnorfuzzy
    - bioconductor-omnipathr

build:
  noarch: generic

about:
  home:  http://colomoto.org/
