package:
  name: colomoto
  version: "0.1"

source:
  git_url: https://github.com/colomoto/colomoto-api.git


requirements:
  run:
    - ginsim
    - maboss
    - notebook

about:
  home:  http://colomoto.org/


