package:
  name: colomoto
  version: "0.2.4"

requirements:
  run:
    - python   >=3.6,<3.7
    - openjdk  >=8.0,<9
    - notebook >=5.2
    - nusmv    2.6.0
    - clingo   5.2.2
    - ginsim   2.9.7
    - maboss   2.0
    - pint     2017.12.19
    - ginsim-python 0.2.91
    - pypint   1.3.93
    - colomoto_jupyter 0.4.2

build:
  noarch: generic

about:
  home:  http://colomoto.org/


