package:
  name: colomoto
  version: "0.2.9"

channels:
  - potassco

requirements:
  run:
    - python   >=3.6,<3.7
    - openjdk  >=8.0,<9
    - notebook >=5.2
    - nusmv    2.6.0
    - nusmv-arctl    2.2.2
    - clingo   5.2.2
    - ginsim   3.0.0b
    - maboss   2.0
    - pint     2018.3.22
    - ginsim-python 0.3.0
    - pypint   1.4.1
    - colomoto_jupyter 0.4.6
    - pymaboss 0.6.2

build:
  noarch: generic

about:
  home:  http://colomoto.org/


