package:
  name: colomoto
  version: "0.2.13"

channels:
  - bioconda
  - conda-forge
  - potassco
  - colomoto

requirements:
  run:
    - python   >=3.6,<3.7
    - openjdk  >=8.0,<9
    - notebook >=5.2
    - nusmv    2.6.0
    - nusmv-arctl    2.2.2
    - clingo   5.3
    - its   20180905
    - ginsim   3.0.0b
    - maboss   2.0
    - pint     2018.11.30
    - ginsim-python 0.3.5
    - pypint   1.5.1
    - colomoto_jupyter 0.5.3
    - pymaboss 0.6.5

build:
  noarch: generic

about:
  home:  http://colomoto.org/
