{% set name = "pystablemotifs" %}
{% set version = "3.0.6" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://github.com/jcrozum/{{ name }}/archive/8d3863a808f9be302676868b9e22b2b5025df481.zip

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pyboolnet >=3.0.9
    - networkx >=2.4.0
    - sympy >=1.5.1
    - pandas >=1.0.0
    - numpy >=1.19.2
    - matplotlib >=3.2.1

about:
  home: https://github.com/jcrozum/pystablemotifs
  summary: A PyBoolNet implementation of stable motif algorithms, including oscillation checking.
