package:
  name: ginsim
  version: "3.0.0b"

source:
  url: http://ginsim.org/sites/default/files/ginsim-dev/GINsim-3.0.0b-SNAPSHOT-jar-with-dependencies.jar

build:
  noarch: generic
  number: 7

requirements:
  run:
    - openjdk
    - clingo
    - nusmv

about:
  home:  http://ginsim.org/

