{% set version = "3.1" %}
{% set patch = ".post20260708" %}

package:
  name: ginsim
  version: "{{ version }}{{ patch }}"

source:
  #url: https://ginsim.github.io/install/GINsim-{{ version }}-with-deps.jar
  url: https://github.com/GINsim/GINsim/releases/download/latest/GINsim-{{ version }}-SNAPSHOT-jar-with-dependencies.jar


build:
  noarch: generic
  number: 0

requirements:
  run:
    - openjdk
    - clingo
    - nusmv

about:
  home:  http://ginsim.org/

