package:
  name: ginsim
  version: "2.9.6"

source:
  url: http://ginsim.org/sites/default/files/ginsim-dev/GINsim-2.9.6-SNAPSHOT-jar-with-dependencies.jar

build:
  noarch: generic
  number: 2 

requirements:
  run:
    - openjdk
    - clingo
    - nusmv

about:
  home:  http://ginsim.org/

