package:
  name: maboss
  version: "2.0"

source:
  url: https://maboss.curie.fr/pub/MaBoSS-env-2.0.tgz

requirements:
  build:
    - flex
    - bison
    - gcc
    - make

about:
  home:  https://maboss.curie.fr


