package:
  name: maboss
  version: "2.0.1"

source:
#  url: https://maboss.curie.fr/pub/MaBoSS-env-2.0.tgz
  git_url: https://github.com/maboss-bkmc/MaBoSS-env-2.0.git
  git_rev: 60da700877d928158d7c6a734f913e0aae41d595

build:
  number: 0

requirements:
  build:
    - flex
    - bison
    - gcc
    - make

about:
  home:  https://maboss.curie.fr


