package:
  name: colomoto_jupyter
  version: "0.3.4"

source:
  git_url: https://github.com/colomoto/colomoto-jupyter.git

build:
  noarch: python
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

about:
  home: https://github.com/colomoto/colomoto-api
  license: LGPL v3+/CeCILL-C
  summary: 'CoLoMoTo helper functions for Juypter integration'
  license_family: LGPL

