package:
  name: colomoto_jupyter
  version: "0.3.4"

source:
  fn: colomoto_jupyter-0.3.4.tar.gz
  url: https://pypi.python.org/packages/c5/af/b7f8f6e1884463244006fedd98460df6d05043c6daeb7d91a4ffdd7d0582/colomoto_jupyter-0.3.4.tar.gz
  md5: 2aea6b639943e1e782a313ed5b54cf01

build:
  noarch: python
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 2

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - networkx >=2.0
    - pydot >=1.2.3
    - pygraphviz

about:
  home: https://github.com/colomoto/colomoto-api
  license: LGPL v3+/CeCILL-C
  summary: 'CoLoMoTo helper functions for Juypter integration'
  license_family: LGPL

