package:
  name: pypint
  version: "1.3.1"

source:
  fn: pypint-1.3.1.tar.gz
  url: https://pypi.python.org/packages/f6/1d/4a38029497cde93a6d9104b9d3877427aa4faa16adc784ac66d4f5ed4792/pypint-1.3.1.tar.gz
  md5: 27b377057e57cca4a391b1dd34d4980b

build:
  noarch: python
  number: 1
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pypint = pypint:main
    #
    # Would create an entry point called pypint that calls pypint.main()

          #    - pint-import=pypint.console:import_model


requirements:
  build:
    - python
    - setuptools
    - networkx >=2.0

  run:
    - pint
    - python
    - colomoto_jupyter >=0.3
    - networkx >=2.0

about:
  home: http://loicpauleve.name/pint
  license: CeCILL
  summary: 'Python interface to Pint'

