{% set version = "5.2.2" %}

package:
  name: clingo
  version: {{ version }}

channels:
  - creditx

source:
  url: https://github.com/potassco/clingo/archive/v{{version}}.tar.gz
# alternative: grab binary tarball directly
#  url: https://github.com/potassco/clingo/releases/download/v{{version}}/clingo-{{version}}-linux-x86_64.tar.gz  # [linux64]
#  url: https://github.com/potassco/clingo/releases/download/v{{version}}/clingo-{{version}}-macos-10.9.tar.gz    # [osx]
#  url: https://github.com/potassco/clingo/releases/download/v{{version}}/clingo-{{version}}-win64.zip            # [win64]

requirements:
  build:
    - cmake
    - gcc-7
    - flex
    - bison
    - python
  run:
    - python

about:
  home:  https://potassco.org/
  license: MIT
  license_file: LICENSE.md


