{% set version = '2.1.3' %}

package:
  name: r-boolnet
  version: {{ version }}

source:
  fn: BoolNet_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/BoolNet_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/BoolNet/BoolNet_{{ version }}.tar.gz


  sha256: 4a35d1bb0db125337d0372098fd2e9072b9c8c4055bce6bc96615cc70d51c4e8


channels:
  - r

build:
  # If this is a new build for the same version, increment the build number.
  number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base
    - r-xml
    - r-igraph >=0.6
    - posix                # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-xml
    - r-igraph >=0.6
#    - r-igraph >=0.6{indent}libgcc  # [not win]

about:
  home: https://CRAN.R-project.org/package=BoolNet
  license: Artistic-2.0
  summary: Provides methods to reconstruct and generate synchronous, asynchronous, probabilistic
    and temporal Boolean networks, and to analyze and visualize attractors in Boolean
    networks.
  license_family: OTHER

# The original CRAN metadata for this package was:

# Package: BoolNet
# Type: Package
# Title: Construction, Simulation and Analysis of Boolean Networks
# Version: 2.1.3
# Date: 2016-06-21
# Authors@R: c(person("Christoph", "Mussel", role = "aut"), person("Martin", "Hopfensitz", role = "aut"), person("Dao", "Zhou", role = "aut"), person(c("Hans", "A."), "Kestler", email = "hans.kestler@uni-ulm.de", role = c("aut", "cre")), person("Armin", "Biere", role = "ctb", comment="contributed PicoSAT code"), person(c("Troy", "D."), "Hanson", role = "ctb", comment="contributed uthash macros"))
# Imports: igraph (>= 0.6), XML
# Description: Provides methods to reconstruct and generate synchronous, asynchronous, probabilistic and temporal Boolean networks, and to analyze and visualize attractors in Boolean networks.
# License: Artistic-2.0
# LazyLoad: yes
# ByteCompile: TRUE
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2016-06-24 13:47:18 UTC; burkovae
# Author: Christoph Mussel [aut], Martin Hopfensitz [aut], Dao Zhou [aut], Hans A. Kestler [aut, cre], Armin Biere [ctb] (contributed PicoSAT code), Troy D. Hanson [ctb] (contributed uthash macros)
# Maintainer: Hans A. Kestler <hans.kestler@uni-ulm.de>
# Repository: CRAN
# Date/Publication: 2016-11-21 12:23:47

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
