{% set version = "9999" %}

package:
  name: espresso-logic-minimizer
  version: {{ version }}

source:
  url: {{ https://github.com/hklarner/pyboolnet/raw/master/binaries/win64/espresso/espresso_win64.exe }}  # [win64]

test:
  commands:
    - espresso -h
