{% set version = "9999" %}

package:
  name: espresso-logic-minimizer
  version: {{ version }}

source:
  url: https://github.com/Gigantua/Espresso/releases/download/Latest/Espresso.exe  # [win64]

build:
  number: 0

test:
  commands:
    - espresso -h
