{% set name = "diptest" %}
{% set version = "0.5.2" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

build:
  number: 1

requirements:
  build:
    - python
    - pip
  run:
    - python {{ python }}
    - numpy >=1.18
    - psutil

about:
  home: https://github.com/RUrlus/diptest
  summary: "A Python/C(++) implementation of Hartigan & Hartigan's dip test for unimodality."
  license: GPL-3.0
