package:
  name: ginsim-python
  version: "0.2.1"

source:
  git_url: https://github.com/GINsim/GINsim-python.git

build:
  noarch: python
  number: 1

requirements:
  run:
    - python
    - ginsim
    - py4j
    - colomoto_jupyter

about:
  home:  http://ginsim.org/


