{% set version = "2.6.0" %}

package:
  name: nusmv
  version: {{ version }}

source:
  url: http://nusmv.fbk.eu/distrib/NuSMV-{{version}}-linux64.tar.gz     # [linux64]
  url: http://nusmv.fbk.eu/distrib/NuSMV-{{version}}-macosx64.tar.gz    # [osx]
  url: http://nusmv.fbk.eu/distrib/NuSMV-{{version}}-win64.tar.gz       # [win64]

requirements:
  build:
    posix # [win64]

about:
  home: http://nusmv.fbk.eu

