{% set version = "2.7.0" %}

package:
  name: nusmv
  version: {{ version }}

source:
  url: http://nusmv.fbk.eu/distrib/{{ version }}/NuSMV-{{version}}-linux64.tar.xz     # [linux64]
  url: http://nusmv.fbk.eu/distrib/{{ version }}/NuSMV-{{version}}-macos-universal.tar.xz    # [osx]
  url: http://nusmv.fbk.eu/distrib/{{ version }}/NuSMV-{{version}}-win64.zip       # [win64]

requirements:
  build:
    posix # [win64]

about:
  home: http://nusmv.fbk.eu

