package:
  name: bns
  version: "1.3"

requirements:
  #build:
  host:
    - {{ compiler('cxx') }}
    - clangxx =15.0.7 # [osx and x86_64]
    - clang =15.0.7 # [osx and x86_64]
    - zlib

test:
  commands:
    - bns


source:
  url: https://people.kth.se/~dubrova/BNS/bns_v1.3.zip
