package:
  name: bns
  version: "1.3"

requirements:
  #build:
    #- clangxx =15.0.7 # [osx and x86_64]
    #- clang =15.0.7 # [osx and x86_64]
  host:
    - {{ compiler('cxx') }}
    - zlib

test:
  commands:
    - bns


source:
  url: https://people.kth.se/~dubrova/BNS/bns_v1.3.zip
