{% set name = "PyBoolNet" %}
{% set version = "3.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hklarner/pyboolnet/archive/refs/tags/{{ version }}.zip

build:
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - bnettoprime
    - click
    - clingo
    - eqntott
    - espresso-logic-minimizer
    - graphviz
    - networkx
    - nusmv-a
    - pyeda

test:
  imports:
    - pyboolnet

about:
  home: https://github.com/hklarner/PyBoolNet
  summary: 'Generation, modification and analysis of Boolean networks'

