{% set name = "PyBoolNet" %}
{% set version = "3.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hklarner/pyboolnet/archive/refs/tags/{{ version }}.zip

channels:
  - colomoto
  - potassco
  - conda-forge

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - bnettoprime
    - click
    - clingo
    - eqntott
    - espresso-logic-minimizer
    - graphviz
    - networkx
    - nusmv-a
    - pyeda

about:
  home: https://github.com/hklarner/PyBoolNet
  summary: 'Generation, modification and analysis of Boolean networks'

