{% set name = "PyBoolNet" %}
{% set version = "3.0.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}.post1

source:
  url: https://github.com/hklarner/pyboolnet/archive/refs/tags/{{ version }}.zip
  patches:
    - py3compat.patch
    - embed-binaries.patch

build:
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - readline=6.2
    - click
    - graphviz
    - networkx

test:
  imports:
    - pyboolnet

about:
  home: https://github.com/hklarner/PyBoolNet
  summary: 'Generation, modification and analysis of Boolean networks'

