{% set name = "PyBoolNet" %}
{% set version = "3.0.16" %}
{% set patch = "" %}

package:
  name: {{ name|lower }}
  version: {{ version }}{{ patch }}

source:
  url: https://github.com/hklarner/pyboolnet/archive/refs/tags/{{ version }}.zip
  patches:
    - embed-binaries.patch

build:
  script: python -m pip install --no-deps --ignore-installed . # [not linux]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - click
    - graphviz
    - networkx
    - nusmv-a  # [linux64]

test:
  imports:
    - pyboolnet

about:
  home: https://github.com/hklarner/PyBoolNet
  summary: 'Generation, modification and analysis of Boolean networks'
