name: autobuild
on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [Ubuntu-latest, windows-latest, macos-latest]
            fail-fast: false
        env:
            OLD_REF: ${{ github.event.before }}
            ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: conda-incubator/setup-miniconda@v4
              with:
                python-version: "3.12"
            - run: conda install -y anaconda-client conda-build conda-verify
            - run: conda config --set anaconda_upload yes
            - run: conda remove --name base -y conda-anaconda-telemetry
            - run: conda info
            - run: conda build -h
            - run: bash -el auto-build-from-push.sh

