{% set version = "1.2.4" %}

package:
  name: pydot
  version: {{ version }}

source:
    git_rev: v{{ version }}
    git_url: https://github.com/erocarrera/pydot

build:
    number: 0
    noarch: python
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - pyparsing >=2.1.4

  run:
    - python
    - pyparsing >=2.1.4

about:
  home: https://github.com/erocarrera/pydot
  license: MIT License
  summary: "Python interface to Graphviz's Dot"
  license_family: MIT

